version: 0.2

env:
  variables:
    DB_HOST: "testdbinstance.crizmtwzkbbn.us-east-1.rds.amazonaws.com"
    DB_USER: "appuser"
    DB_NAME: "movie_db"
    API_PORT: "3000"
  parameter-store:
    DB_PASS: "movie_db_pass"

phases:
  install:
    commands:
      - echo Installing dependencies
      - npm install
  test:
    commands:
      - echo Build started on `date`
      - echo Running tests
      - npm run test
  post_build:
    commands:
      - echo Build completed on `date`